[context.production.environment]
HUGO_VERSION = "0.55.2"

[context.deploy-preview]
HUGO_VERSION = "0.55.2"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.2"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.2"
